# Generated by Django 4.2.1 on 2023-05-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Pass1',
            new_name='Pass',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Pass2',
        ),
    ]
