# Generated by Django 4.2.1 on 2023-05-22 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0004_user1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User1',
            new_name='Users',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
