# Generated by Django 4.2.1 on 2023-05-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0005_rename_user1_users_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Pass2',
            field=models.CharField(max_length=20, verbose_name='Проверка пароля'),
        ),
    ]
