# Generated by Django 4.2.1 on 2023-05-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0009_users1_rename_id_users_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users1',
        ),
        migrations.AddField(
            model_name='users',
            name='Face',
            field=models.ImageField(default='users/default.png', upload_to='users/', verbose_name='Фотография'),
        ),
    ]
