# Generated by Django 4.2.1 on 2023-05-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0011_alter_users_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Face',
            field=models.FileField(upload_to='users', verbose_name='Фотография'),
        ),
    ]
