# Generated by Django 4.2.1 on 2023-06-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0013_alter_users_face'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
