# Generated by Django 4.2.1 on 2023-06-07 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0015_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
