# Generated by Django 4.2.1 on 2023-06-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0016_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('buyer_id', models.IntegerField(verbose_name='id покупателя')),
                ('cart', models.JSONField(verbose_name='Корзина')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('status', models.BooleanField(verbose_name='Статус')),
            ],
        ),
    ]
