# Generated by Django 4.2.1 on 2023-06-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0018_alter_users_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Face',
            field=models.FileField(upload_to='', verbose_name='Фотография'),
        ),
    ]
