# Generated by Django 4.2.1 on 2023-06-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0019_alter_users_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.IntegerField(verbose_name='Статус'),
        ),
    ]
